// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDroInWX0wNnLiofXV3h8nrbfi5fSEOVms',
    appId: '1:382358373808:web:8aa28aa6df8bbc09e50275',
    messagingSenderId: '382358373808',
    projectId: 'je-taime-421eb',
    authDomain: 'je-taime-421eb.firebaseapp.com',
    storageBucket: 'je-taime-421eb.firebasestorage.app',
    measurementId: 'G-2RYKGKPRDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYAofFpv9aZ09sFkxFaRhtv0BBcPNlrOg',
    appId: '1:382358373808:android:f452c400210e6264e50275',
    messagingSenderId: '382358373808',
    projectId: 'je-taime-421eb',
    storageBucket: 'je-taime-421eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvixxoneCPaj7uUtnpPMRuRVreJzmp6g0',
    appId: '1:382358373808:ios:6adc3f0d78408cb0e50275',
    messagingSenderId: '382358373808',
    projectId: 'je-taime-421eb',
    storageBucket: 'je-taime-421eb.firebasestorage.app',
    iosBundleId: 'com.example.jetaime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvixxoneCPaj7uUtnpPMRuRVreJzmp6g0',
    appId: '1:382358373808:ios:6adc3f0d78408cb0e50275',
    messagingSenderId: '382358373808',
    projectId: 'je-taime-421eb',
    storageBucket: 'je-taime-421eb.firebasestorage.app',
    iosBundleId: 'com.example.jetaime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDroInWX0wNnLiofXV3h8nrbfi5fSEOVms',
    appId: '1:382358373808:web:8ff13e8fdf2c014ae50275',
    messagingSenderId: '382358373808',
    projectId: 'je-taime-421eb',
    authDomain: 'je-taime-421eb.firebaseapp.com',
    storageBucket: 'je-taime-421eb.firebasestorage.app',
    measurementId: 'G-8HJW6SZ995',
  );
}
