# Uncomment this line to define a global platform for your project
platform :ios, '12.0'  # Set the minimum iOS version here

# Add any custom configurations here
use_frameworks!  # Required for some plugins (e.g., Firebase)

# Flutter dependencies
flutter_application_path = '../.'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  # Install Flutter dependencies
  install_all_flutter_pods(flutter_application_path)

  # Add additional pods here
  # Example: Firebase dependencies
  # pod 'Firebase/Core'
  # pod 'Firebase/Analytics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'  # Match the platform version
    end
  end
end